Disable Human Readable time stamps
* Temporarily disable Human Readable time stamps function as it's causing issues with subdirectories created by device backups

Traceback (most recent call last):
  File "./degoo_ls", line 235, in <module>
    sys.exit(main())
  File "./degoo_ls", line 212, in main
    raise(e)
  File "./degoo_ls", line 95, in main
    degoo.ls(args.folder, args.long, args.recursive)
  File "/home/growtopiajaw/Degoo-master/degoo/__init__.py", line 1713, in ls
    items = get_children(directory)
  File "/home/growtopiajaw/Degoo-master/degoo/__init__.py", line 1193, in get_children
    __CACHE_CONTENTS__[dir_id] = api.getFileChildren3(dir_id)
  File "/home/growtopiajaw/Degoo-master/degoo/__init__.py", line 634, in getFileChildren3
    times = self._human_readable_times(i['CreationTime'], i['LastModificationTime'], i['LastUploadTime'])
  File "/home/growtopiajaw/Degoo-master/degoo/__init__.py", line 366, in _human_readable_times
    m_secs = int(modification)/1000
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'